In [33]:
import pandas as pd
import numpy as np

In [34]:
state_actions = pd.read_csv('../data/state_action.csv').sample(frac=1)

In [35]:
state_actions.head(12)

0    1    2    3    4    5    6    7    8    9  ...   1575  1576  \
1104  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
235   1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
1799  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
1977  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
1845  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
977   1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
408   1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
581   1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
1117  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
1525  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
2132  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   
1502  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  ...    0.0   0.0   

      1577  1578  1579  1580  1581  1582  1583  1584  
1104   1.0   1.0   0.0   0.0   1.0   0.0   0.0   0.0  
235    1.0   1.0   0.0   0.0   0.0   0.0   1.0   2.0  
1799   1.0   0.0   0.0   0.0   1.0   0.0   0.0   1.0  
1977   1.0   0.0   0.0   0.0   0.0   1.0   0.0   2.0  
1845   1.0   1.0   0.0   1.0   0.0   0.0   0.0   6.0  
977    1.0   1.0   0.0   0.0   1.0   0.0   0.0   7.0  
408    1.0   0.0   0.0   0.0   0.0   1.0   0.0   4.0  
581    1.0   0.0   1.0   0.0   0.0   0.0   0.0   2.0  
1117   1.0   0.0   0.0   0.0   1.0   0.0   0.0   3.0  
1525   1.0   1.0   0.0   0.0   0.0   1.0   0.0   1.0  
2132   1.0   1.0   0.0   0.0   0.0   0.0   1.0   7.0  
1502   1.0   1.0   0.0   0.0   0.0   1.0   0.0   0.0  

[12 rows x 1585 columns]

In [36]:
actions = state_actions.iloc[:, -1:]
states = state_actions.iloc[:, :-1]

In [37]:
states.shape

(2591, 1584)

In [39]:
board_temp = states.iloc[0].as_matrix().reshape((11,9,16))

In [41]:
def print_layer(board, k):
    layer = np.dsplit(board, board.shape[2])[k].reshape((board.shape[0], board.shape[1]))
    print(layer)

In [42]:
for i in range(16):
    print_layer(board_temp, i)

[[ 1.  1.  1.  1.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.  0.  0.  1.  0.]
 [ 0.  1.  0.  1.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.  0.  0.  0.]]
[[ 1.  1.  1.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.  0.  1.]
 [ 0.  0.  1.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  1.  1.  0.  1.  0.  1.  1.  1.]
 [ 1.  1.  0.  1.  1.  0.  1.  0.  1.]
 [ 0.  0.  0.  1.  1.  0.  0.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  1.  